### ISSUE TITLE
Invalid option "scope" when deploying

### ISSUE THREAD

**Issue by michaelsoriano** [pnp/action-cli-deploy#23]
I'm getting an invalid option "scope" when deploying. Using v.2. 

<img width="1011" alt="image" src="https://user-images.githubusercontent.com/5881081/205162645-6ea0522f-f573-406c-9169-855f942a61fd.png">

Per the help docs it looks like the flag should be **-s** 

`-s, --appCatalogScope [appCatalogScope]
Scope of the app catalog: tenant,sitecollection. Default tenant`

Not sure if this is something I configure in YAML file. Please advise.

**Comment by milanholemans** [comment]
Hi @michaelsoriano 

This is indeed an issue on our side. We introduced breaking changes in CLI v6.0.0. We kinda forgot the merge our PR #19 with the breaking changes to the GitHub action.
I just merged it and created a new release `v3.0.0`. Could you verify that it works again please?

**Comment by michaelsoriano** [comment]
Hi @milanholemans, thank you for looking into this. I bumped to v3.0.0 - but getting the same thing? 

<img width="1066" alt="image" src="https://user-images.githubusercontent.com/5881081/205344849-905883b1-0251-40db-9429-cca886695cbf.png">

**Comment by milanholemans** [comment]
Hi @michaelsoriano I seems like the latest release was published a bit too soon before all my changes were made.
I've created a new version `v3.0.1` could you recheck if the problem is fixed?

**Comment by michaelsoriano** [comment]
Looks like the scope flag is fixed. Although I'm getting a 404. I'm not sure if that's related. 

<img width="1137" alt="image" src="https://user-images.githubusercontent.com/5881081/205402757-d93597c3-b471-497f-ad8f-fae0b266c687.png">

Any ideas?

**Comment by milanholemans** [comment]
Would seem strage to me that this is related to the new version. All we did was renaming the option `scope` to `appCatalogScope` in the CLI, all internal code is still the same as before. I'm not exactly sure what could be causing this.
Do you have CLI for Microsoft 365 installed on your local PC? In that case, could you try to run the same command via the CLI to check if it gives the same output? At least on my side, the command seems to be working.

**Comment by michaelsoriano** [comment]
I’ll have to install CLI locally and debug. But the original error is resolved. Thanks again for the quick turnaround..

**Comment by milanholemans** [comment]
Great to hear that it's solved.
Thank you again for logging this issue about the incorrect option name!
